package org.apache.spark.streaming.dstream.generators

import org.apache.spark.sql.SparkSession
import org.apache.spark.streaming.sources.StreamSource

/**
 * Abstract class to represent all kind of generators
 *
 * @tparam T: A primitive type to be generated by StreamGenerator
 * @param source: Underlying distribution source
 * @param session: Already provisioned Spark session to use
 * @param timeout: Waiting time in milliseconds before next sample appears
 */
abstract class StreamGenerator[+T] (val source: StreamSource[T],
                                    val session: SparkSession,
                                    var timeout: Long = 1000
                                  ){
  /**
   * Blocking function that start streaming
   */
  def run(): Unit
}
