package org.apache.spark.streaming.dstream.generators

import org.apache.spark.sql.SparkSession
import org.apache.spark.streaming.sources.StreamSource

/**
 * Abstract class to represent all kind of generators
 *
 * @tparam T: A primitive type to be generated by StreamGenerator
 * @param source: Underlying distribution source
 * @param session: Already provisioned Spark session to use
 * @param window: A window size for sliding function
 * @param step: Repeat slide function for every step
 */
abstract class StreamGenerator[+T] (val source: StreamSource[T],
                                    val session: SparkSession,
                                    val window: Int,
                                    val step: Int
                                  ){
  /**
   * Blocking function that start streaming
   */
  def run(): Unit
}
